export const CALIBER_OPTIONS: string[] = [
  // Common Modern Handgun & Rifle
  '9mm Luger',
  '.45 ACP',
  '.223 Remington',
  '5.56x45mm NATO',
  '.308 Winchester',
  '7.62x51mm NATO',
  '7.62x39mm',
  '.22 LR',
  '12 Gauge',
  '20 Gauge',
  '.410 Bore',
  '16 Gauge',
  '28 Gauge',
  '.380 ACP',
  '.38 Special',
  '.357 Magnum',
  '.44 Magnum',
  '.44 Special',
  '10mm Auto',
  '.40 S&W',
  '5.7x28mm',
  '.300 Blackout',
  '6.5mm Creedmoor',
  '6mm Creedmoor',
  '.300 Winchester Magnum',
  '.270 Winchester',
  '7mm Remington Magnum',
  '.338 Lapua Magnum',
  '6.5 PRC',
  '7mm PRC',
  '.300 PRC',
  '.22-250 Remington',
  '.243 Winchester',
  '.50 BMG',
  '.500 S&W Magnum',
  '.460 S&W Magnum',
  '.454 Casull',
  '.45 Colt (.45 Long Colt)',

  // Historic & Surplus Calibers
  '.30-06 Springfield',
  '.30 Carbine',
  '.30-40 Krag',
  '.30-30 Winchester',
  '.45-70 Government',
  '.405 Winchester',
  '.32 Winchester Special',
  '.35 Remington',
  '.300 Savage',
  '.250-3000 Savage',
  '.303 British',
  '7.62x54mmR',
  '7.92x57mm Mauser (8mm Mauser)',
  '6.5x55mm Swedish Mauser',
  '7.5x55mm Swiss (GP11)',
  '7.65x53mm Argentine Mauser',
  '7x57mm Mauser (7mm Mauser)',
  '6.5x50mmSR Arisaka',
  '7.7x58mm Arisaka',
  '6.5x52mm Carcano',
  '7.35x51mm Carcano',
  '8x56mmR Steyr-Mannlicher',
  '8x50mmR Lebel',
  '7.5x54mm French',
  '7.62x25mm Tokarev',
  '9x18mm Makarov',
  '7.62x38mmR (Nagant)',
  '7.63x25mm Mauser (.30 Mauser)',
  '7.65x21mm Parabellum (.30 Luger)',
  '.455 Webley',
  '.38 S&W (.38/200)',
  '.38-40 Winchester (.38 WCF)',
  '.44-40 Winchester (.44 WCF)',
  '.50 Caliber Muzzleloader',
  '.54 Caliber Muzzleloader',
  '.58 Caliber Minie',
];

export const TYPE_OPTIONS: string[] = [
  'Rifle',
  'Curio & Relic (C&R) Rifle',
  'Military Surplus Service Rifle',
  'Pistol',
  'Curio & Relic (C&R) Handgun',
  'Military Surplus Handgun',
  'Revolver',
  'Shotgun',
  'Single Shot Rifle',
  'Single Shot Shotgun',
  'Single Shot Pistol / Handgun',
  'Antique / Blackpowder',
  'Receiver / Frame',
  'Silencer / Suppressor',
  'SBR (Short-Barreled Rifle)',
  'SBS (Short-Barreled Shotgun)',
  'AOW (Any Other Weapon)',
  'Machine Gun',
  'Destructive Device',
];

export const ACTION_OPTIONS: string[] = [
  // Semi-Automatic & Auto-Loading
  'Semi-Automatic (Direct Impingement)',
  'Semi-Automatic (Short-Stroke Gas Piston)',
  'Semi-Automatic (Long-Stroke Gas Piston)',
  'Semi-Automatic (Direct Blowback)',
  'Semi-Automatic (Delayed Blowback - Roller)',
  'Semi-Automatic (Delayed Blowback - Radial)',
  'Semi-Automatic (Delayed Blowback - Lever)',
  'Semi-Automatic (Short Recoil - Tilting Barrel)',
  'Semi-Automatic (Short Recoil - Rotating Barrel)',
  'Semi-Automatic (Long Recoil)',
  'Semi-Automatic (Inertia Driven)',
  'Semi-Automatic (Gas-Operated Shotgun)',
  'Select-Fire / Fully Automatic',

  // Handgun Firing Systems
  'Striker-Fired',
  'Hammer-Fired (DA/SA)',
  'Single Action Only (SAO)',
  'Double Action Only (DAO)',

  // Bolt Actions
  'Bolt Action (Controlled-Round Feed)',
  'Bolt Action (Push Feed)',
  'Straight-Pull Bolt Action',
  'Bolt Action (Single Shot Target)',
  'Turn-Bolt Action',

  // Lever Actions
  'Lever Action (Tubular Magazine)',
  'Lever Action (Box Magazine / Rotary)',
  'Lever Action (Single Shot)',

  // Pump / Slide Actions
  'Pump Action (Slide Action Shotgun)',
  'Pump Action (Slide Action Rifle)',

  // Revolvers
  'Revolver (Double Action / Single Action)',
  'Revolver (Single Action Only)',
  'Revolver (Double Action Only)',
  'Revolver (Top-Break)',
  'Revolver (Tip-Up)',

  // Break Actions & Hinged
  'Break Action (Single Shot)',
  'Break Action (Over/Under - O/U)',
  'Break Action (Side-by-Side - SxS)',
  'Break Action (Combination / Drilling / Vierling)',

  // Single Shot Falling, Rolling & Pivoting Block
  'Falling Block (Underlever)',
  'Rising Block',
  'Rolling Block',
  'Trapdoor (Hinged Breechblock)',
  'Tilting Block / Martini-Henry',
  'Peabody Action',

  // Muzzleloading & Historic Ignition
  'Muzzleloader (In-Line 209 Primer)',
  'Muzzleloader (Percussion Cap / Caplock)',
  'Muzzleloader (Flintlock)',
  'Muzzleloader (Matchlock)',
  'Muzzleloader (Wheel-lock)',
  'Blackpowder Cartridge (BPC)',

  // Specialty & Multi-Barrel
  'Derringer (Over/Under & Multi-Barrel)',
  'Pepperbox',
  'Gatling / Rotary Action',
];

export const FINISH_OPTIONS: string[] = [
  'Parkerized',
  'Dull Gray Parkerized (Mil-Spec)',
  'Greenish Gray Zinc Parkerized',
  'Blued',
  'High Polish Charcoal Blued',
  'Hot Salt Blued',
  'Color Case Hardened',
  'Niter Blued / Fire Blued',
  'In the White / Armory Bright',
  'Oil Quenched / Browned',
  'Black Suncorite / Enamel Paint',
  'Stainless Steel',
  'Nickel Plated',
  'Matte Black',
  'Cerakote',
  'Nitride',
  'FDE (Flat Dark Earth)',
  'OD Green',
  'Wood/Anodized',
];

export const CONDITION_OPTIONS: string[] = [
  'Factory New',
  'NRA Excellent (98-100%)',
  'NRA Fine (90-95%)',
  'NRA Very Good (75-85%)',
  'NRA Good (60-70%)',
  'NRA Fair (40-50%)',
  'NRA Poor / Relic (<30%)',
  'CMP Collector Grade',
  'CMP Service Grade',
  'CMP Field Grade',
  'CMP Rack Grade',
  'Arsenal Refurbished',
  'All-Matching Numbers',
  'Parts Only',
];

export const AMMO_MANUFACTURERS: string[] = [
  'Federal Premium',
  'Hornady',
  'Winchester',
  'Remington',
  'CCI / Speer',
  'Blazer',
  'PMC',
  'Sellier & Bellot',
  'Fiocchi',
  'Magtech',
  'Aguila',
  'Norma',
  'Lapua',
  'Underwood',
  'Buffalo Bore',
  'Black Hills',
  'Sig Sauer',
  'Monarch',
  'PPU (Prvi Partizan)',
  'Wolf',
  'Tula',
];

export const BULLET_MANUFACTURERS: string[] = [
  'Sierra',
  'Hornady',
  'Nosler',
  'Barnes',
  'Speer',
  'Berger',
  'Lapua',
  "Berry's",
  'Extreme Bullets',
  'Lehigh Defense',
];

export const COMMON_POWDERS: string[] = [
  'Hodgdon Varget',
  'Hodgdon H4350',
  'Hodgdon CFE 223',
  'Hodgdon CFE Pistol',
  'Hodgdon H335',
  'Hodgdon H4895',
  'Hodgdon Titegroup',
  'Hodgdon Clays',
  'Alliant Unique',
  'Alliant Bullseye',
  'Alliant Reloder 15',
  'Alliant Reloder 16',
  'Alliant Power Pistol',
  'Vihtavuori N140',
  'Vihtavuori N320',
  'Vihtavuori N133',
  'Winchester 231 (W231)',
  'Winchester AutoComp',
  'Winchester StaBALL 6.5',
  'IMR 4064',
  'IMR 4895',
  'IMR 4166',
  'Ramshot TAC',
  'Ramshot Big Game',
  'Accurate No. 5',
  'Accurate No. 9',
  'Accurate 2230',
];

export const COMMON_PRIMERS: string[] = [
  'CCI #400 Small Rifle',
  'CCI #450 Small Rifle Magnum',
  'CCI #41 Small Rifle (Military 5.56)',
  'CCI #200 Large Rifle',
  'CCI #250 Large Rifle Magnum',
  'CCI #34 Large Rifle (Military 7.62)',
  'CCI #500 Small Pistol',
  'CCI #550 Small Pistol Magnum',
  'CCI #300 Large Pistol',
  'CCI #350 Large Pistol Magnum',
  'Federal #205M Match Small Rifle',
  'Federal #210M Match Large Rifle',
  'Federal #100 Small Pistol',
  'Federal #150 Large Pistol',
  'Winchester WSR Small Rifle',
  'Winchester WLR Large Rifle',
  'Winchester WSP Small Pistol',
  'Winchester WLP Large Pistol',
  'Remington 7 1/2 Bench Rest Small Rifle',
  'Remington 9 1/2 Large Rifle',
  'Cheddite 209 Shotgun',
  'Winchester 209 Shotgun',
];

export const PRIMER_TYPES: string[] = [
  'Small Pistol',
  'Small Pistol Magnum',
  'Large Pistol',
  'Large Pistol Magnum',
  'Small Rifle',
  'Small Rifle Magnum',
  'Large Rifle',
  'Large Rifle Magnum',
  'Shotgun 209',
];

export const BRASS_MAKES: string[] = [
  'Starline',
  'Lake City (LC)',
  'Lapua',
  'Peterson',
  'Alpha Munitions',
  'Hornady',
  'Winchester',
  'Federal',
  'Remington',
  'Mixed Range Brass',
];

export const SHOTGUN_SHELL_LENGTHS = [
  { value: '', label: 'Select Length...' },
  { value: '1 3/4"', label: '1 3/4" (Mini Shell)' },
  { value: '2 3/4"', label: '2 3/4" (Standard)' },
  { value: '3"', label: '3" (Magnum)' },
  { value: '3 1/2"', label: '3 1/2" (Super Magnum)' },
];

export const SHOTGUN_SHOT_SIZES = [
  { value: '', label: 'Select Shot Size...' },
  { value: 'Slug', label: 'Rifled / Sabot Slug' },
  { value: '000 Buck', label: '000 Buckshot (.36")' },
  { value: '00 Buck', label: '00 Buckshot (.33")' },
  { value: '0 Buck', label: '0 Buckshot (.32")' },
  { value: '1 Buck', label: '1 Buckshot (.30")' },
  { value: '4 Buck', label: '4 Buckshot (.24")' },
  { value: 'BB', label: 'BB (.18")' },
  { value: '2', label: '#2 Birdshot' },
  { value: '4', label: '#4 Birdshot' },
  { value: '6', label: '#6 Birdshot' },
  { value: '7 1/2', label: '#7 1/2 Target / Clay' },
  { value: '8', label: '#8 Target / Clay' },
  { value: '9', label: '#9 Skeet' },
];

export const SHOTGUN_PAYLOADS = [
  { value: '', label: 'Select Payload...' },
  { value: '7/8 oz', label: '7/8 oz' },
  { value: '1 oz', label: '1 oz' },
  { value: '1 1/8 oz', label: '1 1/8 oz' },
  { value: '1 1/4 oz', label: '1 1/4 oz' },
  { value: '1 3/8 oz', label: '1 3/8 oz' },
  { value: '1 1/2 oz', label: '1 1/2 oz' },
];
